
title: Jekyll for web desginers
email: your-email@domain.com
description: "Companiion blog to the lynda.com course, Jekyll for
Web Designers. This site is desgined to
 present Jekyll to web designers in a clear,
 concise way,and provide aa resource and refeerence for those that are new to Jekyll"
#baseurl: "" # the subpath of your site, e.g. /blog
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
tagline: "A basic guide to Jekyll"
markdown: kramdown
#------------------------------------------------
twitter_username: jekyllrb
github_username:  jekyll

# Build settings

theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
